# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-10-22 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='state',
            field=models.CharField(max_length=10),
        ),
    ]
